- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: "yes"
      update_cache: true
      state: latest
  tasks:
    - name: Steps
      include_tasks:
        file: tasks/index.yml
