- hosts: localhost
  vars:
    arch_mapping: # For the Docker installation so arch is right
      x86_64: amd64
      aarch64: arm64
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: "yes"
      update_cache: true
      state: latest
  tasks:
    - name: Steps
      include_tasks:
        file: tasks/main.yml
