- name: Base things
  include_tasks:
      file: ./steps/base.yml

- name: Fonts
  include_tasks:
    file: ./steps/install_fonts.yml

- name: Terminal
  include_tasks:
    file: ./steps/setup_terminal.yml
