---
- name: Install basic bits (git, curl, unzip, tmux, build-essential)
  become: true
  apt:
    pkg:
      - git
      - curl
      - tmux
      - build-essential
      - unzip
      - yadm
    state: latest
...
