---
- name: Get config with yadm
  command: yadm clone -f https://github.com/Captainmango/config-files.git

- name: Add aliases to zshrc
  lineinfile:
    path: "$HOME/.zshrc"
    line: source ~/.zsh_aliases
    create: yes
...
