---
- name: Ensure wget is installed
  become: true
  apt:
    name: wget
    state: present
    update_cache: yes

- name: Create /etc/apt/keyrings directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download GitHub CLI GPG key
  become: true
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'

- name: Add GitHub CLI repository
  become: true
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    filename: github-cli

- name: Update APT cache
  become: true
  apt:
    update_cache: yes

- name: Install GitHub CLI
  become: true
  apt:
    name: gh
    state: present
...

