---
- name: Download Mise install script
  become: true
  get_url:
    url: https://mise.run
    dest: /tmp/mise_install.sh

- name: Run Mise installation script
  become: true
  command: sh /tmp/mise_install.sh
...
