---
- name: Download Mise install script
  get_url:
    url: https://mise.run
    dest: /tmp/mise_install.sh

- name: Run Mise installation script
  command: sh /tmp/mise_install.sh

- name: Create .asdf directory (For symlinking lang installs for IDEs)
  file:
    path: "$HOME/.asdf"
    state: directory

- name: Symlink the Mise folder with the .asdf folder
  file:
    src: ~/.local/share/mise
    dest: ~/.asdf
    force: true
    owner: "{{ lookup('env', 'USER') }}"
    state: link
...
