---
- name: Ensure fonts directory exists
  become: true
  file:
    path: "/usr/share/fonts"
    state: directory

- name: Ensure Meslo font directory exists
  become: true
  file:
    path: "/usr/share/fonts/truetype/MesloLGSDZ Nerd Font"
    state: directory

- name: Download Meslo font and unpack into MesloLGSDZ Nerd Font folder
  become: true
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Meslo.zip
    dest: "/usr/share/fonts/truetype/MesloLGSDZ Nerd Font"
    remote_src: yes
...
