---
- name: Download Neovim and upack
  become: true
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/v0.10.1/nvim-linux64.tar.gz
    dest: "/opt"
    remote_src: yes

- name: Add nvim bin to PATH
  become: true
  lineinfile:
    path: ~/.zshrc
    line: export PATH="$PATH:/opt/nvim-linux64/bin"
    create: yes
...