---
- name: Install ZSH
  become: true
  apt:
    pkg:
      - zsh

- name: Ensure .zshrc exists
  file:
    path: ~/.zshrc
    state: touch

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: ohmyzsh_result.rc != 0 or 'FAILED' in ohmyzsh_result.stderr

- name: Change default shell to zsh
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh

- name: Set ZSH_THEME in .zshrc
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME'
    line: ZSH_THEME="robbyrussell"
    create: yes

- name: Install Starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship
  become: true

- name: Add Starship init to .zshrc
  lineinfile:
    path: ~/.zshrc
    line: 'eval "$(starship init zsh)"'
    create: yes

- name: Set EDITOR in .zshrc
  lineinfile:
    path: ~/.zshrc
    line: export EDITOR=nvim
    create: yes
...
