---
name: Test Installation

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "30 5 * * 1" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run test container
        run: ./bin/test-container.sh
...
